name: Release NPM package

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build
      - run: npm run test:3d

  release:
    needs: [build]
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Set tag
        id: tagName
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - run: npm ci

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
