name: Release NPM package

on:
  push:
    tags: ['v*']

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node build
    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run build
      - run: npm run test

  release:
    needs: [build]
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds

      - name: Set tag
        id: tagName
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - run: npm ci
      - run: npm run build
      - run: npm publish
